export { default as CountUpNumber } from "@watheia/molecular.molecules.count-up-number"
export { default as SectionHeader } from "./SectionHeader"
export { default as IconAlternate } from "./IconAlternate"
export { default as SwiperImage } from "./SwiperImage"
export { default as DescriptionCta } from "@watheia/molecular.molecules.description-cta"
export { default as OverlapedImages } from "./OverlapedImages"
export { default as SwiperNumber } from "./SwiperNumber"
export { default as TypedText } from "./TypedText"
