export { default as CountUpNumber } from "@watheia/molecules.count-up-number"
export { default as SectionHeader } from "./SectionHeader"
export { default as IconAlternate } from "@watheia/molecules.icon-alternate"
export { default as SwiperImage } from "./SwiperImage"
export { default as DescriptionCta } from "@watheia/molecules.description-cta"
export { default as OverlappedImages } from "@watheia/molecules.overlapped-images"
export { default as SwiperNumber } from "./SwiperNumber"
export { default as TypedText } from "./TypedText"
